package main

import (
	"fmt"
	"net/http"
	"net/http/fcgi"
)

func handler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Header().Set("Content-type", "text/plain; charset=utf-8")
	fmt.Fprintln(w, "This was generated by Go running as a FastCGI app")
}

func main() {
	/*
	 *	
	 *	Everything that is done here should be setup code etc. which is retained between calls
	 *	
	 */
	http.HandleFunc("/", handler)
	// This is what actually concurrently handles requests
	if err := fcgi.Serve(nil, nil); err != nil {
			panic(err)
	}
}
